#!/usr/bin/env bash

target=../cfebs.github.com

# generate site to the local _site dir
jekyll

# copy it to our destination
cp -R _site/* $target

# cleanup
rm "$target/`basename $0`"
rm "$target/.gitmodules"
rm "$target/.gitignore"
git add .; git commit -am  "`date +%F_%H-%M_%s`";
