#!/usr/bin/env bash

target=../cfebs.github.com
here=`pwd`

# generate site to the local _site dir
jekyll

# copy it to our destination
cp -R _site/* $target
cd $target

# cleanup
rm `basename $0`
rm .gitmodules
rm .gitignore
# push out
git add .; git commit -am  "Update `basename $target`: `date +%F_%H-%M_%s`"; git push origin master;

cd $here
